name: SimpleReport
version: "1.0.0"
main: madversal\simplereport\Main
api: 5.0.0
author: MadVersal
description: ¡a simple report system ready for use!
website: https://github.com/MadVersal/SimpleReport
softdepend: CortexPE

permissions:
  simplereport.use:
    description: Allows players to use the report command
    default: true
  simplereport.admin:
    description: Allows admins to view reports and receive notifications
    default: op
  simplereport.viewreports:
    description: Allows viewing all reports
    default: op
