# Message format for admin notifications when a report is submited
admin-notification-format: "ยงc[REPORT] ยง7{reporter} reported {reported} for: {reason}"

# Cooldown between reports (in seconds) to prevent spam
report-cooldown: 60

# Minimum length for report reasons
min-reason-length: 5

# Maximum length for report reasons
max-reason-length: 100

# Number of reports to show per page in /viewreports
reports-per-page: 5

# Setup the webhook
report.webhook: 'Your webhook here'

# Auto-cleanup settings
cleanup:
  # Enable automatic cleanup of old resolved reports if the reports not set resolved cant remove it
  enabled: true
  # Delete resolved reports older than X days
  days-old: 30
  # Cleanup interval in hours
  interval-hours: 24

# Additional features
features:
  # Allow players to see their own reports
  allow-self-view: true
  # Log all reports to console
  console-logging: true
  # Broadcast to all admins when a report is made
  broadcast-to-admins: true
